import QtQuick
import QtQuick.Layouts
import NordicHeadunit

Rectangle {
    id: root
    color: NordicTheme.colors.bg.primary
    
    // Explicit height for proper layouting (Fix #4: Responsive height)
    implicitHeight: NordicTheme.layout.statusBarHeight
    
    // Public properties
    property string title: qsTr("Home")
    
    // Driving/Focus Mode - simplified UI for driving
    // Note: drivingModeChanged signal is auto-generated by QML for this property
    property bool drivingMode: false
    
    // Constants
    readonly property int updateIntervalMs: 60000  // 60 seconds for HH:mm display
    readonly property int lowBatteryThreshold: 20
    readonly property int criticalBatteryThreshold: 10
    
    // Helper functions
    function safeGet(obj, prop, fallback) {
        return (typeof obj !== "undefined" && typeof obj[prop] !== "undefined") ? obj[prop] : fallback
    }
    
    // Computed properties from services with safe access
    readonly property bool isWifiConnected: safeGet(SystemSettings, "wifiEnabled", false)
    readonly property bool isBluetoothConnected: safeGet(SystemSettings, "bluetoothEnabled", false)
    readonly property bool isNavigating: safeGet(NavigationService, "isNavigating", false)
    readonly property bool isPlaying: safeGet(MediaService, "isPlaying", false)
    readonly property bool isInCall: safeGet(PhoneService, "inCall", false)
    readonly property bool isCharging: safeGet(VehicleService, "isCharging", false)
    readonly property bool useMetric: safeGet(SystemSettings, "useMetric", true)
    
    readonly property int batteryLevel: safeGet(VehicleService, "batteryLevel", 85)
    readonly property real outsideTemp: safeGet(VehicleService, "outsideTemperature", 21)
    
    // Service connectivity status - warns user when data may be stale
    readonly property bool servicesConnected: typeof VehicleService !== "undefined" && 
                                               typeof SystemSettings !== "undefined"
    
    // Formatted temperature with unit based on settings
    readonly property string temperature: {
        var temp = useMetric ? outsideTemp : (outsideTemp * 9/5 + 32)
        return Math.round(temp) + (useMetric ? qsTr("°C") : qsTr("°F"))
    }
    
    // Battery color based on level
    readonly property color batteryColor: {
        if (batteryLevel <= criticalBatteryThreshold) return NordicTheme.colors.semantic.error
        if (batteryLevel <= lowBatteryThreshold) return NordicTheme.colors.semantic.warning
        return NordicTheme.colors.text.primary
    }
    
    // Time and date properties
    property string currentTime: Qt.formatTime(new Date(), "HH:mm")
    property string currentDate: Qt.formatDate(new Date(), "ddd d MMM")
    
    // Precise Timer logic (Fixed: Sync to minute boundary)
    Timer {
        id: clockTimer
        interval: 60000
        repeat: true
        running: true
        onTriggered: root.updateDateTime()
    }
    
    function syncClock() {
        var now = new Date()
        var msToNextMinute = (60 - now.getSeconds()) * 1000 - now.getMilliseconds()
        // Wait for next minute, then start regular 60s timer
        singleShotTimer.interval = msToNextMinute + 50 // +50ms buffer
        singleShotTimer.start()
        root.updateDateTime()
    }
    
    Timer {
        id: singleShotTimer
        repeat: false
        onTriggered: {
            root.updateDateTime()
            clockTimer.restart() // Start the regular minute loop
        }
    }
    
    function updateDateTime() {
        var format = (typeof SystemSettings !== "undefined" && SystemSettings.use24HourFormat) ? "HH:mm" : "h:mm AP"
        // Return simulated time if available
        var now = (typeof SystemSettings !== "undefined") ? SystemSettings.currentDateTime : new Date()
        
        currentTime = Qt.formatTime(now, format)
        currentDate = Qt.formatDate(now, "ddd d MMM")
    }
    
    Component.onCompleted: syncClock()
    
    // Pull Down Gesture Area (Global)
    // Pull Down Gesture Area (Global)
    MouseArea {
        anchors.fill: parent
        z: 0 
        
        property real startY: 0
        property real startX: 0
        property bool isDragging: false
        
        // Settings for drag recognition (Android-like feel)
        readonly property int dragThreshold: 40
        readonly property int maxHorizontalDrift: 100 // Prevent accidental firing when swiping sideways
        
        onPressed: (mouse) => { 
            startY = mouse.y 
            startX = mouse.x
            isDragging = false
        }
        
        onPositionChanged: (mouse) => {
            if (isDragging) return
            
            var dy = mouse.y - startY
            var dx = Math.abs(mouse.x - startX)
            
            // Analyze the drag direction
            if (dy > dragThreshold) {
                // If we drifted too much horizontally, ignore it (user might be swiping a widget)
                if (dx > maxHorizontalDrift) return
                
                // Commit to the action
                root.settingsClicked()
                isDragging = true
                mouse.accepted = false // Let lower items take over if needed? No, we consumed it.
            }
        }
        
        onReleased: (mouse) => {
            if (!isDragging && (mouse.y - startY > dragThreshold)) {
                // Catch quick flicks
                root.settingsClicked()
            }
            isDragging = false
        }
    }
    
    // Separator Component
    Component {
        id: separator
        Rectangle {
            width: 1; height: 16
            color: NordicTheme.colors.text.tertiary
            opacity: 0.3
            anchors.verticalCenter: parent.verticalCenter
        }
    }
    
    // Main Layout
    RowLayout {
        anchors.fill: parent
        anchors.leftMargin: NordicTheme.spacing.space_4
        anchors.rightMargin: NordicTheme.spacing.space_4
        spacing: NordicTheme.spacing.space_4
        
        // ═══════════════════════════════════════════════════════════════════
        // LEFT: Time and Date
        // ═══════════════════════════════════════════════════════════════════
        Row {
            spacing: NordicTheme.spacing.space_2
            Layout.alignment: Qt.AlignVCenter
            
            NordicText {
                text: root.currentTime
                type: NordicText.Type.TitleSmall
                color: NordicTheme.colors.text.primary
                anchors.verticalCenter: parent.verticalCenter
            }
            
            Loader { sourceComponent: separator }
            
            NordicText {
                text: root.currentDate
                type: NordicText.Type.BodySmall
                color: NordicTheme.colors.text.tertiary
                anchors.verticalCenter: parent.verticalCenter
            }
        }
        
        // Center spacer
        Item { Layout.fillWidth: true }
        
        // ═══════════════════════════════════════════════════════════════════
        // CENTER: Page Title + Active Indicators
        // ═══════════════════════════════════════════════════════════════════
        Row {
            spacing: NordicTheme.spacing.space_2
            Layout.alignment: Qt.AlignVCenter
            
            // Navigation
            StatusIndicator {
                active: root.isNavigating
                iconSource: "qrc:/qt/qml/NordicHeadunit/assets/icons/map.svg"
                color: Theme.accent
                Accessible.name: qsTr("Navigation active")
            }
            
            // Call
            StatusIndicator {
                active: root.isInCall
                iconSource: "qrc:/qt/qml/NordicHeadunit/assets/icons/phone.svg"
                color: NordicTheme.colors.semantic.success
                Accessible.name: qsTr("Call in progress")
            }
            
            NordicText {
                text: root.title
                type: NordicText.Type.BodyMedium
                color: Theme.textSecondary
                anchors.verticalCenter: parent.verticalCenter
            }
            
            // Media
            StatusIndicator {
                active: root.isPlaying
                iconSource: "qrc:/qt/qml/NordicHeadunit/assets/icons/music.svg"
                color: Theme.accent
                Accessible.name: qsTr("Media playing")
            }
        }
        
        // Center spacer
        Item { Layout.fillWidth: true }
        
        // ═══════════════════════════════════════════════════════════════════
        // RIGHT: Status Indicators
        // ═══════════════════════════════════════════════════════════════════
        // ═══════════════════════════════════════════════════════════════════
        // RIGHT: Status Indicators
        // ═══════════════════════════════════════════════════════════════════
        RowLayout {
            spacing: NordicTheme.spacing.space_3
            Layout.alignment: Qt.AlignVCenter
            
            // Temperature
            NordicText { 
                text: root.temperature
                type: NordicText.Type.BodySmall
                color: NordicTheme.colors.text.primary
                Layout.alignment: Qt.AlignVCenter
                Accessible.name: qsTr("Outside temperature: ") + root.temperature
            }
            
            Loader { 
                sourceComponent: separator 
                Layout.alignment: Qt.AlignVCenter
            }
            
            // Battery
            StatusIndicator {
                active: true
                iconSource: "qrc:/qt/qml/NordicHeadunit/assets/icons/battery.svg"
                text: root.batteryLevel + "%" + (root.isCharging ? " ⚡" : "")
                iconColor: root.batteryColor
                color: root.batteryColor
                Layout.alignment: Qt.AlignVCenter
                Accessible.name: qsTr("Battery ") + root.batteryLevel + qsTr("%")
            }
            
            // Bluetooth
            StatusIndicator {
                visible: !NordicTheme.layout.isCompact // Hide in Compact mode
                active: root.isBluetoothConnected
                iconSource: "qrc:/qt/qml/NordicHeadunit/assets/icons/bluetooth.svg"
                Layout.alignment: Qt.AlignVCenter
                Accessible.name: qsTr("Bluetooth connected")
            }
            
            // WiFi - Shows connectivity status (removed misleading "5G" label)
            StatusIndicator {
                visible: !NordicTheme.layout.isCompact // Hide in Compact mode
                active: true 
                iconSource: "qrc:/qt/qml/NordicHeadunit/assets/icons/wifi.svg"
                opacity: root.isWifiConnected ? 1.0 : 0.4
                color: root.isWifiConnected ? NordicTheme.colors.text.primary : NordicTheme.colors.text.tertiary
                Layout.alignment: Qt.AlignVCenter
                Accessible.name: root.isWifiConnected ? qsTr("WiFi connected") : qsTr("WiFi disconnected")
            }
            
            // Audio Mute Indicator (Epic 2.3) - Only visible when muted
            StatusIndicator {
                active: typeof SystemSettings !== "undefined" && SystemSettings.muted === true
                iconSource: "qrc:/qt/qml/NordicHeadunit/assets/icons/volume_off.svg"
                color: NordicTheme.colors.semantic.warning
                Layout.alignment: Qt.AlignVCenter
                Accessible.name: qsTr("Audio muted")
            }
            
            // System Alert Indicator (Epic 2.5) - Shows when notifications pending
            StatusIndicator {
                active: typeof NotificationService !== "undefined" && NotificationService.unreadCount > 0
                iconSource: "qrc:/qt/qml/NordicHeadunit/assets/icons/edit.svg"
                color: NordicTheme.colors.semantic.info
                Layout.alignment: Qt.AlignVCenter
                Accessible.name: qsTr("Notifications pending")
                
                // Badge for count
                Rectangle {
                    visible: parent.active && NotificationService.unreadCount > 0
                    anchors.top: parent.top
                    anchors.right: parent.right
                    anchors.topMargin: -2
                    anchors.rightMargin: -2
                    width: 8; height: 8
                    radius: 4
                    color: NordicTheme.colors.semantic.error
                }
            }
            
            Loader { 
                sourceComponent: separator 
                Layout.alignment: Qt.AlignVCenter
            }
            
            // Driving Mode Toggle - 44px minimum touch target for automotive safety
            // Epic 6.1: Locked while actively driving (speed > 0)
            Rectangle {
                id: focusModeButton
                width: 44; height: 44
                radius: 22
                color: root.drivingMode ? Theme.accent : "transparent"
                Layout.alignment: Qt.AlignVCenter
                opacity: focusModeEnabled ? 1.0 : 0.5
                
                // Driving lockout: disable when vehicle is moving
                readonly property bool focusModeEnabled: typeof VehicleService === "undefined" || VehicleService.speed === 0
                
                Behavior on color { ColorAnimation { duration: 200 } }
                
                Rectangle {
                    anchors.centerIn: parent
                    width: 32; height: 32
                    radius: 16
                    color: root.drivingMode ? Theme.accent : Theme.surfaceAlt
                    border.color: root.drivingMode ? Theme.accent : NordicTheme.colors.border.muted
                    border.width: 1
                    
                    NordicIcon {
                        anchors.centerIn: parent
                        source: "qrc:/qt/qml/NordicHeadunit/assets/icons/focus.svg"
                        size: NordicIcon.Size.SM
                        color: root.drivingMode ? NordicTheme.colors.text.inverse : Theme.textSecondary
                    }
                }
                
                MouseArea {
                    id: focusMouseArea
                    anchors.fill: parent
                    cursorShape: focusModeButton.focusModeEnabled ? Qt.PointingHandCursor : Qt.ForbiddenCursor
                    enabled: focusModeButton.focusModeEnabled
                    onClicked: root.drivingMode = !root.drivingMode
                }
                
                Accessible.role: Accessible.Button
                Accessible.name: root.drivingMode ? qsTr("Exit Focus Mode") : qsTr("Enable Focus Mode")
            }
        }
    }
    
    // Bottom border
    Rectangle {
        anchors.bottom: parent.bottom
        width: parent.width
        height: 1
        color: NordicTheme.colors.border.muted
    }
    
    signal settingsClicked()
    signal notificationClicked()
}
